Syncing with template (#13)
* chore(template): merge template changes :up:

* Revert renaming

* Update requirements.txt

* Update requirements.txt

---------

Co-authored-by: pavetok <github-action@actions-template-sync.noreply.github.com>
Co-authored-by: Pavel Vetokhin <p.vetokhin@gmail.com>
Co-authored-by: Pavel Vetokhin <pavetok@users.noreply.github.com>

diff --git a/.github/workflows/beyond-doubt.yaml b/.github/workflows/beyond-doubt.yaml
--- a/.github/workflows/beyond-doubt.yaml
+++ b/.github/workflows/beyond-doubt.yaml
@@ -54,7 +54,7 @@ jobs:
       - uses: mikepenz/action-junit-report@v4.0.3
         if: ${{ !cancelled() && (steps.images.outcome == 'success' || steps.images.outcome == 'failure') }}
         with:
-          check_name: Unit test report
+          check_name: Unit test report (${{ matrix.env.dev }})
           report_paths: "**/target/surefire-reports/TEST-*.xml"
           require_tests: "${{ steps.images.outcome == 'failure' }}"
           fail_on_failure: false
@@ -62,7 +62,7 @@ jobs:
       - uses: mikepenz/action-junit-report@v4.0.3
         if: ${{ !cancelled() && (steps.images.outcome == 'success' || steps.images.outcome == 'failure') }}
         with:
-          check_name: Integration test report
+          check_name: Integration test report (${{ matrix.env.dev }})
           report_paths: "**/target/failsafe-reports/TEST-*.xml"
           require_tests: "${{ steps.images.outcome == 'failure' }}"
           fail_on_failure: false
@@ -212,7 +212,7 @@ jobs:
     name: Stack reporting
     timeout-minutes: 5
     needs: [stack-testing]
-    if: ${{ !cancelled() && (needs.stack-testing.result == 'success' || needs.stack-testing.result == 'failure') }}
+    if: ${{ !cancelled() && (contains(needs.*.result, 'success') || contains(needs.*.result, 'failure')) }}
     runs-on: ubuntu-22.04
     permissions:
       checks: write
@@ -224,6 +224,17 @@ jobs:
         with:
           check_name: E2E test report
           report_paths: "artifacts/e2e-test-report-*/**/TEST-*.xml"
-          require_tests: "${{ needs.stack-testing.result == 'failure' }}"
           fail_on_failure: false
           job_summary: false
+
+  everything-is-fine:
+    name: Everything is fine
+    needs: [stack-publishing, stack-reporting]
+    runs-on: ubuntu-latest
+    timeout-minutes: 10
+    if: ${{ always() }}
+    steps:
+      - if: ${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'skipped') || contains(needs.*.result, 'cancelled') }}
+        run: |
+          echo "::error::Something went wrong"
+          exit 1
diff --git a/.github/workflows/convincing.yaml b/.github/workflows/convincing.yaml
--- a/.github/workflows/convincing.yaml
+++ b/.github/workflows/convincing.yaml
@@ -13,7 +13,7 @@ on:
   workflow_dispatch:
 
 jobs:
-  uu-to-images:
+  up-to-images:
     name: Up to images
     timeout-minutes: 10
     runs-on: ubuntu-22.04
@@ -56,17 +56,21 @@ jobs:
           require_tests: "${{ steps.images.outcome == 'failure' }}"
           fail_on_failure: false
           job_summary: false
-      - name: Always empty E2E test report. See https://github.com/orgs/community/discussions/13690
-        uses: mikepenz/action-junit-report@v4.0.3
-        if: ${{ !cancelled() }}
-        with:
-          check_name: E2E test report
-          require_tests: false
-          fail_on_failure: false
-          job_summary: false
       - uses: actions/upload-artifact@v3.1.3
         if: ${{ !cancelled() }}
         with:
           name: test-coverage-report
           path: tools/target/coverage
           if-no-files-found: ignore
+
+  everything-is-fine:
+    name: Everything is fine
+    needs: [up-to-images]
+    runs-on: ubuntu-latest
+    timeout-minutes: 10
+    if: ${{ always() }}
+    steps:
+      - if: ${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'skipped') || contains(needs.*.result, 'cancelled') }}
+        run: |
+          echo "::error::Something went wrong"
+          exit 1
diff --git a/.github/workflows/sanity.yaml b/.github/workflows/sanity.yaml
--- a/.github/workflows/sanity.yaml
+++ b/.github/workflows/sanity.yaml
@@ -5,6 +5,9 @@ on:
   pull_request:
     branches-ignore:
       - main
+      - feature/**
+      - bugfix/**
+      - chore/**
   workflow_dispatch:
 
 jobs:
@@ -40,3 +43,15 @@ jobs:
           require_tests: "${{ steps.binaries.outcome == 'failure' }}"
           fail_on_failure: false
           job_summary: false
+
+  everything-is-fine:
+    name: Everything is fine
+    needs: [up-to-binaries]
+    runs-on: ubuntu-latest
+    timeout-minutes: 10
+    if: ${{ always() }}
+    steps:
+      - if: ${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'skipped') || contains(needs.*.result, 'cancelled') }}
+        run: |
+          echo "::error::Something went wrong"
+          exit 1
